### ISSUE TITLE
ParseField String ?

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Optparse-Generic-Library#1]
I was just trying it (well I know it is not even on hackage yet ;-) and converting this simple program:
https://github.com/PierreR/vCloudApi/blob/master/src/Option.hs

But it chokes on `String`.

`wreq` is using both `String` and `Text` so it makes sense to have some field of type `String` in this example.

Will you support this use case ?

**Comment by Gabriella439** [comment]
So with a little bit of hacking it is possible to add a `ParseFields` (not `ParseField`) instance for `String`.  The standard way to do this is to add a new `parseListOfField` method to the `ParseField` class:

``` haskell
class ParseField a where
    ...
    parseListOfField
        :: Maybe Text
        -- ^ Field label
        -> Parser [a]
    parseListOfField = fmap many parseField
```

... and have the `ParseFields` instance for lists use `parseListOfField`:

``` haskell
instance ParseField a => ParseFields [a] where
    parseFields = parseListOfField
```

... and then only override the default implementation of `parseListOfField` only for the `ParseField` instance for `Char`:

``` haskell
instance ParseField Char
    ...
    parseListOfField = parseString "STRING"
```

However, there's an issue if you add a `ParseField` instance for `String`, because `ParseField` is a super-class of `ParseFields` and therefore you would have to add a `ParseFields` instance for `String`.  However, that would conflict with the `ParseFields` instance for lists.

Without a `ParseField` instance for `String` you won't be able to parse a field of type `[String]` (or a top-level `[String]`), which would be pretty surprising for the user since that's a reasonably common use case.

I **could** remove the `ParseFields` super-class constraint from `ParseField` to resolve that, which is what I might end up doing.  I would like to keep that super-class constraint if possible so that people who implement `ParseField` don't forget to implement `ParseFields` (and also implement `ParseRecord` which is a super-class of `ParseFields`), but if I can't figure out another way to do this when I will just remove the super-class constraint.

**Comment by Gabriella439** [comment]
So I ended up implementing this as described.  Enjoy!
