### ISSUE TITLE
Typo in getOnly example?

### ISSUE THREAD

**Issue by tfausak** [Gabriel439/Haskell-Optparse-Generic-Library#20]
https://github.com/Gabriel439/Haskell-Optparse-Generic-Library/blob/809d998fa6d51d6d85b5894ae9ff4fcf51cd8341/src/Options/Generic.hs#L507

``` hs
instance ParseRecord MyType where
    parseRecord = fmap getOnly parseRecord
```

Should that instead say `parseRecord = fmap getOnly parseFields`?

**Comment by Gabriella439** [comment]
Not a typo.  Note that `fmap getOnly parseFields` would be a type error for two separate reasons:
- (A) `Only` (intentionally) does not have a `ParseFields` instance
- (B) `parseFields` is a function of two arguments:

``` haskell
parseFields :: Maybe Text -> Maybe Text -> Parser a
```

The correct translation for what you have in mind would be:

``` haskell
parseRecord = parseFields Nothing Nothing
```

... which is exactly equivalent to what you get with `fmap getOnly parseFields` (because that's what the `Generic` `ParseRecord` instance for `Only` will auto-generate).

To understand why `fmap getOnly parseRecord` is consistent with the documentation, note that the `ParseRecord` instance for `Only` is:

``` haskell
instance ParseFields a => ParseRecord (Only a)
```

So if you parse a value of type `Only a` it will use defer to the equivalent `ParseFields` instance for the type `a`, and then `getOnly` just unwraps the `Only` newtype.

**Comment by tfausak** [comment]
Oops. Thank you!

**Comment by Gabriella439** [comment]
You're welcome! :)
