### ISSUE TITLE
Custom ParseFields Instance - not behaving as expected?

### ISSUE THREAD

**Issue by adarqui** [Gabriel439/Haskell-Optparse-Generic-Library#24]
Hey Garbriel,

I'm not sure if this should work or not. I have the code compiling, but, I don't see the "lang" field of my Options record showing up in any of the command line options. I know the tutorial says you can't embed records within records, but what about sum types?

https://github.com/adarqui/obesity/blob/master/src/System/Obesity/Types.hs#L79

```
...
  lang            :: Lang         <?> "language to generate",
...

data Lang
  = Lang_Haskell
  | Lang_Purescript
  | Lang_Golang
  deriving (Generic, Typeable)

instance ParseRecord Lang

instance ParseFields Lang where
  parseFields h m = do
    case m of
      Nothing   -> do
        let fs =  OptA.metavar "LANG"
               <> maybe mempty (OptA.help . T.unpack) h
        OptA.argument auto fs
      Just name -> pure Lang_Haskell
```

That's what i'm trying to do. Is that possible? If so, i'm not sure why the "lang" field of the Options record isn't showing up.

```
> :main --help
Obesity

Usage: <interactive> [--separateModules] [--explicitImports] [--explicitExports]
                     [--randomNumTypes] [--randomNumFields] [--numTypes INT]
                     [--numFields INT] --dir TEXT

Available options:
  -h,--help                Show this help text
  --separateModules        create types in separate files or the same file
  --explicitImports        be explicit about imports
  --explicitExports        be explicit about exports
  --randomNumTypes         randomly generate types from 1 to numTypes
  --randomNumFields        randomly generate fields within types, from 1 to
                           numFields
  --numTypes INT           number of types to create
  --numFields INT          number of fields per type
  --dir TEXT               directory to save files into
```

Thanks!

**Comment by Gabriella439** [comment]
The second argument to `parseFields` represents whether or not the data type you defined has a field label.  It's `Nothing` is the field is unlabeled and `Just "the label name"` if it is labeled.

For your example data type the field is labeled `lang`, so `m = Just "lang"`.  This means that your code takes the second branch of your case expression:

``` haskell
instance ParseFields Lang where
  parseFields h m = do
    case m of
      ...
      Just name -> pure Lang_Haskell  --  <= Here
```

Since you skip the `Nothing` branch you never register an option parser for your field, which is why it doesn't show up in the `--help` output.

In your case, though, a simple solution is to take advantage of the face that the `ParseField` class provides a default implementation if your type implement `Read` and `Typeable`, so you can just write:

```
data Lang
  = Lang_Haskell
  | Lang_Purescript
  | Lang_Golang
  deriving (Generic, Read, Typeable)

instance ParseField Lang
instance ParseFields
```

**Comment by adarqui** [comment]
@Gabriel439 Hey man, sorry I never saw this. Thanks alot, I will try this out!

**Comment by Gabriella439** [comment]
You're welcome!
