### ISSUE TITLE
Default action for sum types

### ISSUE THREAD

**Issue by koterpillar** [Gabriel439/Haskell-Optparse-Generic-Library#30]
I have a use case for three commands, one of which should be the "default" one, i.e.

```
run foo # action one
run bar # action two
run # action three, the default
```

The following type can give me three actions, but they all have to be explicitly specified (`run default` instead of `run`):

```haskell
data Action = Foo | Bar | Default
```

How about including the `DefaultArg` type with the following implementation?

```haskell
data DefaultArg a
    = JustArg a
    | DefaultArg

instance ParseRecord a =>
         ParseRecord (DefaultArg a) where
    parseRecord =
        fmap JustArg parseRecord <|> fmap (\() -> DefaultArg) parseRecord
```

This can also be extended to support 

```haskell
getRecordDefault :: ParseRecord a => a -> Text -> IO a
getRecordPureDefault :: ParseRecord a => a -> [Text] -> Maybe a
```

(Note that `getRecordPureDefault a args` isn't `fromMaybe a $ getRecordPure args`, because the invalid arguments will still result in a `Nothing`.)

**Comment by koterpillar** [comment]
An alternative is to make `whenEmpty :: Maybe a` a member of `ParseRecord` class, so that:

```haskell
instance ParseRecord Action where
    whenEmpty = Just Default
```

gives the expected behavior.

This one doesn't make much sense for single constructor types, though.

**Comment by Gabriella439** [comment]
The issue with a `DefaultArg` type is that it only works when there are no additional options to parse because the `DefaultArg` constructor can't store any values

For example, suppose I had the following type that I wanted to decode command line options into:

```haskell
data Options = Add { user :: Text } | Remove { user :: Text }
```

... and I wanted to make `Add` the default action if no subcommand were supplied.  If I used `DefaultArg` there would be no place to store the required `user` field if the user ran:

```bash
$ ./example --user John
```

`whenEmpty` has the same issue, which is that you can't create a default value of type `Options` without doing some command line parsing to retrieve the required `user` field

**Comment by koterpillar** [comment]
That is something I didn't think of, I was only solving a problem when the default action didn't have any parameters. The `whenEmpty` will have to specify the `user` upfront.

I'll try to think of some type-level trickery of marking the default alternative then.
